TOPDIR  = ../../..
include $(TOPDIR)/make.inc
include $(CONFIG_PATH)config/make.$(CONFIG).inc

BUILD_DIR        = build.$(CONFIG)
SOURCE_FILES     = $(wildcard *.cc)
DEP_FILES        = $(patsubst %.cc, $(BUILD_DIR)/%.d, $(SOURCE_FILES))


HEADER_FILES     = $(call rwildcard, $(TOPDIR)/ulmBLAS/, *.h *.tcc)
PCH_FILES        = $(subst %, %.gch, $(HEADER_FILES))
OBJECT_FILES     = $(patsubst %.cc, $(BUILD_DIR)/$(PREFIX)%.o, $(SOURCE_FILES))

CXXFLAGS        += -I $(TOPDIR) -DADD_

CBLAS_LIB        = $(TOPDIR)/$(CBLAS_LIB_NAME)
CBLAS_HEADER     = $(TOPDIR)/$(CBLAS_HEADER_NAME)

CBLAS_DEFS       = -D'BLAS_HEADER=<$(CBLAS_HEADER_NAME)>' \
                   -D'CBLAS(x)=$(CBLAS_PREFIX) \#\# x' \
                   -D'ULMBLAS(x)=$(ULMBLAS_PREFIX) \#\# x' \
                   -D'CBLAS_H=$(CBLAS_INCLUDE_GUARD)'

all $(CONFIG): $(CBLAS_LIB) $(CBLAS_HEADER)

$(CBLAS_LIB) : $(OBJECT_FILES)
	$(RM)  $(CBLAS_LIB)
	ar cru $(CBLAS_LIB) $(OBJECT_FILES)
	ranlib $(CBLAS_LIB)

$(CBLAS_HEADER) : cblas.h.in
	$(CXX) -x c++ $(CBLAS_DEFS) -E -CC cblas.h.in | grep -v "^#\s\d*\s" | sed  's,^ *#,#,' > $(CBLAS_HEADER)

$(BUILD_DIR) :
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/%.o : %.cc $(CBLAS_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	$(CXX) $(CBLAS_DEFS) $(CXXFLAGS) -c -o $@ $<

$(BUILD_DIR)/%.d : %.cc $(CBLAS_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	set -e; $(CXX) $(CXXFLAGS) $(CBLAS_DEFS) -MM $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(BUILD_DIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

ifneq ($(MAKECMDGOALS),clean)
-include $(DEP_FILES)
endif

.PHONY : clean
clean :
	$(RM) -r $(BUILD_DIR)
	$(RM) $(CBLAS_LIB)
	$(RM) $(CBLAS_HEADER)
