TOPDIR = ../..

include $(TOPDIR)/make.inc
include $(CONFIG_PATH)config/make.$(CONFIG).inc

TESTBASE_SOURCE_FILES = $(wildcard *.f)
TESTBASE_TARGET_FILES = $(patsubst %.f, %, $(TESTBASE_SOURCE_FILES))

F77BLAS_LIB           = $(TOPDIR)/$(F77BLAS_LIB_NAME)
LDLIBS               += $(F77BLAS_LIB) -lstdc++

F77MAKEFILE_PATH      = $(TOPDIR)/interfaces/blas/F77/

all :  $(TESTBASE_TARGET_FILES)
	set -e; $(RM) DBLAT1.SUMM.$(SUMMARY_SUFFIX); ./dblat1 > $(TOPDIR)/DBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; $(RM) DBLAT2.SUMM.$(SUMMARY_SUFFIX); sed 's,DBLAT2\.SUMM,DBLAT2.SUMM.$(SUMMARY_SUFFIX),' < dblat2.dat.in > dblat2.dat; ./dblat2 < dblat2.dat; mv DBLAT2.SUMM.$(SUMMARY_SUFFIX) $(TOPDIR)
	set -e; $(RM) DBLAT3.SUMM.$(SUMMARY_SUFFIX); sed 's,DBLAT3\.SUMM,DBLAT3.SUMM.$(SUMMARY_SUFFIX),' < dblat3.dat.in > dblat3.dat; ./dblat3 < dblat3.dat; mv DBLAT3.SUMM.$(SUMMARY_SUFFIX) $(TOPDIR)

$(TESTBASE_TARGET_FILES): $(F77BLAS_LIB)

.PHONY : $(F77BLAS_LIB)
$(F77BLAS_LIB) $(CONFIG) :
	make -C $(F77MAKEFILE_PATH) -f Makefile.config $(MAKECMDGOALS) CONFIG_PATH='$(CURDIR)/' CONFIG=$(CONFIG)

% : %.o
	$(CXX) $(LDFLAGS) $(LDLIBS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $<

check: $(TARGET_FILES)
	@set -e; $(RM) DBLAT2.SUMM; ./dblat2 < dblat2.dat; \
	echo "Results for level 2 BLAS double precision: DBLAT2.SUMM"
	@set -e; $(RM) DBLAT3.SUMM; ./dblat3 < dblat3.dat; \
	echo "Results for level 3 BLAS double precision: DBLAT3.SUMM"

clean: $(CONFIG)
	$(RM) $(TARGET_FILES) $(TOPDIR)/*.SUMM.*
