TOPDIR             = ../../..
CBLASMAKEFILE_PATH = ../../blas/C

include $(TOPDIR)/make.inc
include $(CBLASMAKEFILE_PATH)/config/make.$(CONFIG).inc

BUILD_DIR        = build.$(CONFIG)
SOURCE_FILES     = $(wildcard *.cc)
DEP_FILES        = $(patsubst %.cc, $(BUILD_DIR)/%.d, $(SOURCE_FILES))
OBJECT_FILES     = $(patsubst %.cc, $(BUILD_DIR)/$(PREFIX)%.o, $(SOURCE_FILES))

CXXFLAGS        += -I $(TOPDIR)

CLAPACK_LIB      = $(TOPDIR)/$(CLAPACK_LIB_NAME)
CBLAS_HEADER     = $(TOPDIR)/$(CBLAS_HEADER_NAME)
CLAPACK_HEADER   = $(TOPDIR)/$(CLAPACK_HEADER_NAME)

CLAPACK_DEFS     = -D'BLAS_HEADER=<$(CBLAS_HEADER_NAME)>' \
                   -D'LAPACK_HEADER=<$(CLAPACK_HEADER_NAME)>' \
                   -D'CLAPACK(x)=$(CLAPACK_PREFIX) \#\# x' \
                   -D'ULMLAPACK(x)=$(ULMLAPACK_PREFIX) \#\# x' \
                   -D'CLAPACK_H=$(CLAPACK_INCLUDE_GUARD)'

all $(CONFIG): $(CLAPACK_LIB) $(CLAPACK_HEADER)

$(CLAPACK_LIB) : $(OBJECT_FILES)
	$(RM)  $(CLAPACK_LIB)
	ar cru $(CLAPACK_LIB) $(OBJECT_FILES)
	ranlib $(CLAPACK_LIB)

$(CBLAS_HEADER) :
	make -C $(CBLASMAKEFILE_PATH) -f Makefile.config $(CBLAS_HEADER)

$(CLAPACK_HEADER) : clapack.h.in $(CBLAS_HEADER)
	$(CXX) -x c++ $(CLAPACK_DEFS) -E -CC clapack.h.in | grep -v "^#\s\d*\s" | sed  's,^ *#,#,' > $(CLAPACK_HEADER)

$(BUILD_DIR) :
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/%.o : %.cc $(CBLAS_HEADER) $(CLAPACK_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	$(CXX) $(CLAPACK_DEFS) $(CXXFLAGS) -c -o $@ $<

$(BUILD_DIR)/%.d : %.cc $(CBLAS_HEADER) $(CLAPACK_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	set -e; $(CXX) $(CXXFLAGS) $(CLAPACK_DEFS) -MM $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(BUILD_DIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

ifneq ($(MAKECMDGOALS),clean)
-include $(DEP_FILES)
endif

.PHONY : clean
clean :
	$(RM) -r $(BUILD_DIR)
	$(RM) $(CBLAS_HEADER)
	$(RM) $(CLAPACK_HEADER)
	$(RM) $(CLAPACK_LIB)
