TOPDIR     = ..
BENCH_DIR  = $(BENCH_DIR_PREFIX).$(CONFIG)
include $(TOPDIR)/make.inc
include $(CONFIG_PATH)config/make.$(CONFIG).inc

SOURCE_FILES = l1blastst.c l2blastst.c l3blastst.c lutst.c
OBJECT_FILES = $(patsubst %.c, $(BENCH_DIR)/%.o,   $(SOURCE_FILES))
TARGETS      = $(patsubst %.c, $(BENCH_DIR)/xd%,   $(SOURCE_FILES))

ATLAS_BLAS_LIBS   ?= $(patsubst %, $(TOPDIR)/%, $(ATLAS_BLAS_LIB_NAMES))
ATLAS_LAPACK_LIBS ?= $(patsubst %, $(TOPDIR)/%, $(ATLAS_LAPACK_LIB_NAMES))
REF_BLAS_LIBS     ?= $(patsubst %, $(TOPDIR)/%, $(REF_BLAS_LIB_NAMES))
RUN_BENCH_CMD      = $(BENCH_DIR)/$(BENCH_CMD)

CFLAGS = $(BENCH_CFLAGS)

all: $(OBJECT_FILES) $(TARGETS)

$(BENCH_DIR) :
	mkdir -p $(BENCH_DIR)

$(ATLAS_BLAS_LIBS) : $(CONFIG_PATH)config/make.$(CONFIG).inc
	$(MAKE_ATL_BLAS)

$(ATLAS_LAPACK_LIBS) : $(CONFIG_PATH)config/make.$(CONFIG).inc
	$(MAKE_ATL_LAPACK)

$(REF_BLAS_LIBS) : $(CONFIG_PATH)config/make.$(CONFIG).inc
	$(MAKE_REF_BLAS)

$(BENCH_DIR)/%.o : %.c $(ATLAS_BLAS_LIBS) $(ATLAS_LAPACK_LIBS) $(REF_BLAS_LIBS) $(filter-out $(wildcard $(BENCH_DIR)), $(BENCH_DIR))
	$(CC) $(CFLAGS) -o $@ -c $<

$(BENCH_DIR)/xd% : $(BENCH_DIR)/%.o $(ATLAS_BLAS_LIBS) $(REF_BLAS_LIBS) $(filter-out $(wildcard $(BENCH_DIR)), $(BENCH_DIR))
	$(CXX) $(LDFLAGS) -o $@ $< -lstdc++ $(LDLIBS) libtstatlas.a $(ATLAS_LAPACK_LIBS) $(ATLAS_BLAS_LIBS) $(REF_BLAS_LIBS)

.PHONY : clean
clean:
	rm -fr $(BENCH_DIR)

