#ifndef ULMBLAS_LEVEL2_LEVEL2_H
#define ULMBLAS_LEVEL2_LEVEL2_H 1

#include <ulmblas/level2/gbmtv.h>
#include <ulmblas/level2/gbmv.h>
#include <ulmblas/level2/gemv.h>
#include <ulmblas/level2/ger.h>
#include <ulmblas/level2/hblmv.h>
#include <ulmblas/level2/hbumv.h>
#include <ulmblas/level2/helmv.h>
#include <ulmblas/level2/helr.h>
#include <ulmblas/level2/helr2.h>
#include <ulmblas/level2/hplmv.h>
#include <ulmblas/level2/hplr.h>
#include <ulmblas/level2/hplr2.h>
#include <ulmblas/level2/hpumv.h>
#include <ulmblas/level2/hpur.h>
#include <ulmblas/level2/hpur2.h>
#include <ulmblas/level2/level2.h>
#include <ulmblas/level2/sblmv.h>
#include <ulmblas/level2/sbumv.h>
#include <ulmblas/level2/splmv.h>
#include <ulmblas/level2/splr.h>
#include <ulmblas/level2/splr2.h>
#include <ulmblas/level2/spumv.h>
#include <ulmblas/level2/spur.h>
#include <ulmblas/level2/spur2.h>
#include <ulmblas/level2/sylmv.h>
#include <ulmblas/level2/sylr.h>
#include <ulmblas/level2/sylr2.h>
#include <ulmblas/level2/tblmtv.h>
#include <ulmblas/level2/tblmv.h>
#include <ulmblas/level2/tblstv.h>
#include <ulmblas/level2/tblsv.h>
#include <ulmblas/level2/tbumtv.h>
#include <ulmblas/level2/tbumv.h>
#include <ulmblas/level2/tbustv.h>
#include <ulmblas/level2/tbusv.h>
#include <ulmblas/level2/tplmtv.h>
#include <ulmblas/level2/tplmv.h>
#include <ulmblas/level2/tplstv.h>
#include <ulmblas/level2/tplsv.h>
#include <ulmblas/level2/tpumtv.h>
#include <ulmblas/level2/tpumv.h>
#include <ulmblas/level2/tpustv.h>
#include <ulmblas/level2/tpusv.h>
#include <ulmblas/level2/trlmv.h>
#include <ulmblas/level2/trlsv.h>
#include <ulmblas/level2/trumv.h>
#include <ulmblas/level2/trusv.h>

#endif // ULMBLAS_LEVEL2_LEVEL2_H
