TOPDIR  = ../../..
include $(TOPDIR)/make.inc
include $(CONFIG_PATH)config/make.$(CONFIG).inc

BUILD_DIR       := build.$(CONFIG)
SOURCE_FILES    := $(wildcard *.f) $(wildcard *.cc)


ifdef INCLUDE_PCH
    DEP_FILES   := $(ULMBLAS_D)
else
    DEP_FILES   := $(patsubst %.cc, $(BUILD_DIR)/%.d, $(filter %.cc, $(SOURCE_FILES)))
endif

OBJECT_FILES    := $(patsubst %.f, $(BUILD_DIR)/%.o, \
                          $(patsubst %.cc, $(BUILD_DIR)/%.o, $(SOURCE_FILES)))

CXXFLAGS        += -I $(TOPDIR)

F77BLAS_LIB     := $(TOPDIR)/$(F77BLAS_LIB_NAME)
F77BLAS_HEADER  := $(TOPDIR)/$(F77BLAS_HEADER_NAME)

F77BLAS_DEFS    := -D'BLAS_HEADER=<$(F77BLAS_HEADER_NAME)>' \
                   -D'F77BLAS(x)= x \#\# $(F77BLAS_SUFFIX)' \
                   -D'F77BLAS_H=$(F77BLAS_INCLUDE_GUARD)'

all: $(F77BLAS_LIB) $(F77BLAS_HEADER)

$(ULMBLAS_PCH) : $(ULMBLAS_H) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	$(CXX) $(CXXFLAGS) -x c++-header -c -o $@ $<

$(ULMBLAS_D) : $(ULMBLAS_H)
	set -e; $(CXX) $(CXXFLAGS) -x c++-header $(F77BLAS_DEFS) -MM $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(BUILD_DIR)/\1.h.gch $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

$(F77BLAS_LIB) : $(OBJECT_FILES)
	$(RM)  $(F77BLAS_LIB)
	ar cru $(F77BLAS_LIB) $(OBJECT_FILES)
	ranlib $(F77BLAS_LIB)

$(F77BLAS_HEADER) : f77blas.h.in
	$(CXX) -x c++ $(F77BLAS_DEFS) -E -CC f77blas.h.in | grep -v "^#\s\d*\s" | sed  's,^ *#,#,' > $(F77BLAS_HEADER)

$(BUILD_DIR) :
	mkdir -p $(BUILD_DIR) $(BUILD_DIR)/asum  $(BUILD_DIR)/dot $(BUILD_DIR)/iamax $(BUILD_DIR)/nrm2

$(BUILD_DIR)/%.o : %.cc $(ULMBLAS_PCH) $(F77BLAS_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	$(CXX) $(F77BLAS_DEFS) $(INCLUDE_PCH) $(CXXFLAGS) -c -o $@ $<

$(BUILD_DIR)/%.o : %.f  $(F77BLAS_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	$(FC) $(F77BLAS_DEFS) $(FFLAGS) -c -o $@ $<

$(BUILD_DIR)/%.d : %.cc $(F77BLAS_HEADER) $(filter-out $(wildcard $(BUILD_DIR)), $(BUILD_DIR))
	set -e; $(CXX) $(CXXFLAGS) $(F77BLAS_DEFS) -MM $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(BUILD_DIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) $@.$$$$

ifneq ($(MAKECMDGOALS),clean)
-include $(DEP_FILES)
endif

.PHONY : clean
clean:
	$(RM) -r $(BUILD_DIR)
	$(RM) $(F77BLAS_LIB)
	$(RM) $(F77BLAS_HEADER)
