TOPDIR       = ../..
CONFIG_PATH ?= $(CURDIR)/
CONFIG_FILE  = $(CONFIG_PATH)config/make.$(CONFIG).inc

include $(TOPDIR)/make.inc
include $(CONFIG_FILE)

SOURCE_FILES  = $(wildcard *.c) $(wildcard *.f)
OBJECT_FILES  = $(patsubst %.c, %.o, $(patsubst %.f, %.o, $(SOURCE_FILES)))

C_DBLAT1      = c_dblat1_$(CONFIG)
C_DBLAT1_DEPS = c_dblat1.o c_dblas1.o

C_DBLAT2      = c_dblat2_$(CONFIG)
C_DBLAT2_DEPS = c_dblat2.o c_dblas2.o auxiliary.o c_d2chke.o c_xerbla.o cblas_globals.o

C_DBLAT3      = c_dblat3_$(CONFIG)
C_DBLAT3_DEPS = c_dblat3.o c_dblas3.o auxiliary.o c_d3chke.o c_xerbla.o cblas_globals.o

TARGETS       = $(C_DBLAT1) $(C_DBLAT2) $(C_DBLAT3)

CMAKEFILE_PATH        = $(TOPDIR)/interfaces/blas/C/

FFLAGS               += -I $(TOPDIR)
CFLAGS               += -I $(TOPDIR) -DADD_

CBLAS_LIB             = $(TOPDIR)/$(CBLAS_LIB_NAME)
LDLIBS               += $(CBLAS_LIB) -lstdc++
CBLAS_HEADER          = $(TOPDIR)/$(CBLAS_HEADER_NAME)

CBLAS_DEFS           += -D'BLAS_HEADER=<$(CBLAS_HEADER_NAME)>' \
                        -D'ULMBLAS(x)=$(CBLAS_PREFIX) \#\# x' \
                        -D'CBLAS_H=$(CBLAS_INCLUDE_GUARD)'

CFLAGS               += $(CBLAS_DEFS)
CXXFLAGS             += $(CBLAS_DEFS)

all :  $(TARGETS)
	set -e; ./c_dblat1_$(CONFIG) > $(TOPDIR)/C_DBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; ./c_dblat2_$(CONFIG) > $(TOPDIR)/C_DBLAT2.SUMM.$(SUMMARY_SUFFIX) < din2;
	set -e; ./c_dblat3_$(CONFIG) > $(TOPDIR)/C_DBLAT3.SUMM.$(SUMMARY_SUFFIX) < din3;

$(TARGETS): $(CBLAS_LIB) $(OBJECT_FILES)

$(OBJECT_FILES) : $(CONFIG_FILE) $(CBLAS_LIB)

.PHONY: $(CBLAS_LIB)
$(CBLAS_LIB) : $(CONFIG_FILE)
	make -C $(CMAKEFILE_PATH) -f Makefile.config $(MAKECMDGOALS) CONFIG_PATH='$(CONFIG_PATH)/' CONFIG=$(CONFIG)

$(C_DBLAT1) : $(C_DBLAT1_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT1_DEPS) $(LDLIBS)

$(C_DBLAT2) : $(C_DBLAT2_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT2_DEPS) $(LDLIBS)

$(C_DBLAT3) : $(C_DBLAT3_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT3_DEPS) $(LDLIBS)

clean:
	$(RM) $(TARGETS) $(OBJECT_FILES) $(TOPDIR)/C_*.SUMM.*
	make -C $(CMAKEFILE_PATH) -f Makefile.config clean CONFIG_PATH='$(CONFIG_PATH)/' CONFIG=$(CONFIG)
