TOPDIR       = ../..
CONFIG_PATH ?= $(CURDIR)/
CONFIG_FILE  = $(CONFIG_PATH)config/make.$(CONFIG).inc

include $(TOPDIR)/make.inc
include $(CONFIG_FILE)

SOURCE_FILES  = $(wildcard *.c) $(wildcard *.f)
OBJECT_FILES  = $(patsubst %.c, %.o, $(patsubst %.f, %.o, $(SOURCE_FILES)))

C_SBLAT1      = c_sblat1_$(CONFIG)
C_SBLAT1_DEPS = c_sblat1.o c_sblas1.o

C_DBLAT1      = c_dblat1_$(CONFIG)
C_DBLAT1_DEPS = c_dblat1.o c_dblas1.o

C_CBLAT1      = c_cblat1_$(CONFIG)
C_CBLAT1_DEPS = c_cblat1.o c_cblas1.o

C_ZBLAT1      = c_zblat1_$(CONFIG)
C_ZBLAT1_DEPS = c_zblat1.o c_zblas1.o

C_SBLAT2      = c_sblat2_$(CONFIG)
C_SBLAT2_DEPS = c_sblat2.o c_sblas2.o auxiliary.o c_s2chke.o c_xerbla.o

C_DBLAT2      = c_dblat2_$(CONFIG)
C_DBLAT2_DEPS = c_dblat2.o c_dblas2.o auxiliary.o c_d2chke.o c_xerbla.o

C_CBLAT2      = c_cblat2_$(CONFIG)
C_CBLAT2_DEPS = c_cblat2.o c_cblas2.o auxiliary.o c_c2chke.o c_xerbla.o

C_ZBLAT2      = c_zblat2_$(CONFIG)
C_ZBLAT2_DEPS = c_zblat2.o c_zblas2.o auxiliary.o c_z2chke.o c_xerbla.o

C_SBLAT3      = c_sblat3_$(CONFIG)
C_SBLAT3_DEPS = c_sblat3.o c_sblas3.o auxiliary.o c_s3chke.o c_xerbla.o

C_DBLAT3      = c_dblat3_$(CONFIG)
C_DBLAT3_DEPS = c_dblat3.o c_dblas3.o auxiliary.o c_d3chke.o c_xerbla.o

C_CBLAT3      = c_cblat3_$(CONFIG)
C_CBLAT3_DEPS = c_cblat3.o c_cblas3.o auxiliary.o c_c3chke.o c_xerbla.o

C_ZBLAT3      = c_zblat3_$(CONFIG)
C_ZBLAT3_DEPS = c_zblat3.o c_zblas3.o auxiliary.o c_z3chke.o c_xerbla.o

TARGETS       = $(C_SBLAT1) $(C_DBLAT1) $(C_CBLAT1) $(C_ZBLAT1) $(C_SBLAT2) $(C_DBLAT2) $(C_CBLAT2) $(C_ZBLAT2) $(C_SBLAT3) $(C_DBLAT3) $(C_CBLAT3) $(C_ZBLAT3)

CMAKEFILE_PATH        = $(TOPDIR)/interfaces/blas/C/

FFLAGS               += -I $(TOPDIR)
CFLAGS               += -I $(TOPDIR) -DADD_

CBLAS_LIB             = $(TOPDIR)/$(CBLAS_LIB_NAME)
LDLIBS               += $(CBLAS_LIB) -lstdc++
CBLAS_HEADER          = $(TOPDIR)/$(CBLAS_HEADER_NAME)

CBLAS_DEFS           += -D'BLAS_HEADER=<$(CBLAS_HEADER_NAME)>' \
                        -D'ULMBLAS(x)=$(CBLAS_PREFIX) \#\# x' \
                        -D'CBLAS_H=$(CBLAS_INCLUDE_GUARD)'

CFLAGS               += $(CBLAS_DEFS)
CXXFLAGS             += $(CBLAS_DEFS)

all :  $(TARGETS)
	set -e; ./$(C_SBLAT1) > $(TOPDIR)/C_SBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; ./$(C_DBLAT1) > $(TOPDIR)/C_DBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; ./$(C_CBLAT1) > $(TOPDIR)/C_CBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; ./$(C_ZBLAT1) > $(TOPDIR)/C_ZBLAT1.SUMM.$(SUMMARY_SUFFIX);
	set -e; ./$(C_SBLAT2) > $(TOPDIR)/C_SBLAT2.SUMM.$(SUMMARY_SUFFIX) < sin2;
	set -e; ./$(C_DBLAT2) > $(TOPDIR)/C_DBLAT2.SUMM.$(SUMMARY_SUFFIX) < din2;
	set -e; ./$(C_CBLAT2) > $(TOPDIR)/C_CBLAT2.SUMM.$(SUMMARY_SUFFIX) < cin2;
	set -e; ./$(C_ZBLAT2) > $(TOPDIR)/C_ZBLAT2.SUMM.$(SUMMARY_SUFFIX) < zin2;
	set -e; ./$(C_SBLAT3) > $(TOPDIR)/C_SBLAT3.SUMM.$(SUMMARY_SUFFIX) < sin3;
	set -e; ./$(C_DBLAT3) > $(TOPDIR)/C_DBLAT3.SUMM.$(SUMMARY_SUFFIX) < din3;
	set -e; ./$(C_CBLAT3) > $(TOPDIR)/C_CBLAT3.SUMM.$(SUMMARY_SUFFIX) < cin3;
	set -e; ./$(C_ZBLAT3) > $(TOPDIR)/C_ZBLAT3.SUMM.$(SUMMARY_SUFFIX) < zin3;

$(TARGETS): $(CBLAS_LIB) $(OBJECT_FILES)

$(OBJECT_FILES) : $(CONFIG_FILE)

$(C_SBLAT1) : $(C_SBLAT1_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_SBLAT1_DEPS) $(LDLIBS)

$(C_DBLAT1) : $(C_DBLAT1_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT1_DEPS) $(LDLIBS)

$(C_CBLAT1) : $(C_CBLAT1_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_CBLAT1_DEPS) $(LDLIBS)

$(C_ZBLAT1) : $(C_ZBLAT1_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_ZBLAT1_DEPS) $(LDLIBS)


$(C_SBLAT2) : $(C_SBLAT2_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_SBLAT2_DEPS) $(LDLIBS)

$(C_DBLAT2) : $(C_DBLAT2_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT2_DEPS) $(LDLIBS)

$(C_CBLAT2) : $(C_CBLAT2_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_CBLAT2_DEPS) $(LDLIBS)

$(C_ZBLAT2) : $(C_ZBLAT2_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_ZBLAT2_DEPS) $(LDLIBS)


$(C_SBLAT3) : $(C_SBLAT3_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_SBLAT3_DEPS) $(LDLIBS)

$(C_DBLAT3) : $(C_DBLAT3_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_DBLAT3_DEPS) $(LDLIBS)

$(C_CBLAT3) : $(C_CBLAT3_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_CBLAT3_DEPS) $(LDLIBS)

$(C_ZBLAT3) : $(C_ZBLAT3_DEPS)
	$(CXX) $(LDFLAGS) $(LDF77FLAGS) $(LDF77LIBS) -o $@ $(C_ZBLAT3_DEPS) $(LDLIBS)


clean:
	$(RM) $(TARGETS) $(OBJECT_FILES) $(TOPDIR)/C_*.SUMM.*
